name: AI Commit Message

on: [push]

jobs:
  commit_message:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout 
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Replace commit message with AI-generated title
        uses: salehhashemi1992/ai-commit-message@v0.3.0
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4 
