
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  actions: read
  checks: write    

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore FFF.Clipboard.sln

    - name: Build Release
      run: msbuild FFF.Clipboard.sln /p:Configuration=Release /m

    - name: Install NUnit.ConsoleRunner    
      run: nuget install NUnit.ConsoleRunner -Version 3.16.3
      
    - name: Run tests
      run: ./NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe FFF.Clipboard.Tests/bin/Release/FFF.Clipboard.Tests.dll
