name: ".NET Framework : CI, Test, Report"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-latest
    steps:  
    - name: Checkout 
      uses: actions/checkout@v4.1.1
      
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Restore NuGet packages
      run: nuget restore FFF.Clipboard.sln
      
    - name: Build Release
      run: msbuild FFF.Clipboard.sln /p:Configuration=Release /m
      
    - name: Upload test artifact
      uses: actions/upload-artifact@v4.2.0
      if: success()     
      with:
        name: FFF.Clipboard.Tests
        path: FFF.Clipboard.Tests/bin/Release/
      
  tests:
    needs: build 
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4.1.1
    - name: Install NUnit.ConsoleRunner    
      run: nuget install NUnit.ConsoleRunner -Version 3.16.3
    - name: Download test artifact
      uses: actions/download-artifact@v4.1.1
      with:
        name: FFF.Clipboard.Tests
        path: artifact    
    - name: Delete test artifact
      uses: geekyeggo/delete-artifact@v4.1.0
      with:
         name: FFF.Clipboard.Tests
         token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: ./NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe ./artifact/FFF.Clipboard.Tests.dll --result ./report/TestResults.xml
          
    - name: Upload test-report artifact
      uses: actions/upload-artifact@v4.2.0
      if: success()
      with:
        name: test-results
        path: ./report
        
  reports:
    needs: tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Fetch transform code
        run: |
          wget https://raw.githubusercontent.com/nunit/nunit-transforms/master/nunit3-junit/nunit3-junit.xslt
        shell: bash
      - name: Download test artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: test-results   

      - name: kkkt
        run: ls 

      - name: Install NUnit
        run: |
          nuget install NUnit.Console -Version 3.16.1
        shell: bash
        
      - name: Transform NUnit3 to JUnit
        run: |
          $xml = Resolve-Path "TestResults.xml" # Replace with your specific file name
          $output = Join-Path ($pwd.Path) "transform_junit.xml" # Output file name
          $xslt = New-Object System.Xml.Xsl.XslCompiledTransform;
          $xslt.Load("nunit3-junit.xslt");
          $xslt.Transform($xml, $output);
        shell: pwsh


      - name: kkkt
        run: ls

      - uses: dorny/test-reporter@v1.4.2
        with:
          name: "NUnit tests for $1"
          path: "*_junit.xml"
          reporter: jest-junit
