name: ".NET Framework : CI, Test, Report"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-latest
    steps:  
    - name: Checkout 
      uses: actions/checkout@v4.1.1
      
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Restore NuGet packages
      run: nuget restore FFF.Clipboard.sln
      
    - name: Build Release
      run: msbuild FFF.Clipboard.sln /p:Configuration=Release /m
      
    - name: Upload test artifact
      uses: actions/upload-artifact@v4.2.0
      if: success()     
      with:
        name: FFF.Clipboard.Tests
        path: FFF.Clipboard.Tests/bin/Release/
