# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: 'CI'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  SOLUTION_NAME: FFF.Clipboard
  TEST_PROJECT_NAME: FFF.Clipboard.Tests
  
jobs:
  build:
    runs-on: windows-latest
    steps:  
    - name: Checkout 
      uses: actions/checkout@v4.1.1
      
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_NAME }}.sln
      
    - name: Build Release
      run: msbuild ${{ env.SOLUTION_NAME }}.sln /p:Configuration=Release /m
      
    - name: Upload test artifact
      uses: actions/upload-artifact@v4.3.1
      if: success()     
      with:
        name: ${{ env.TEST_PROJECT_NAME }}
        path: ${{ env.TEST_PROJECT_NAME }}/bin/Release/
      
  tests:
    needs: build 
    runs-on: windows-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4.1.1
      
    - name: Install NUnit.ConsoleRunner    
      run: nuget install NUnit.ConsoleRunner -Version 3.16.3
      
    - name: Download test artifact
      uses: actions/download-artifact@v4.1.2
      with:
        name: ${{ env.TEST_PROJECT_NAME }}
        path: artifact    
        
    - name: Delete test artifact
      uses: geekyeggo/delete-artifact@v4.1.0
      with:
         name: ${{ env.TEST_PROJECT_NAME }}
         token: ${{ secrets.GITHUB_TOKEN }}
         
    - name: Run tests
      run: ./NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe ./artifact/${{ env.TEST_PROJECT_NAME }}.dll --result ./report/TestResults.xml
          
    - name: Upload test-report artifact
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: test-results
        path: ./report
        
  reports:
    needs: tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Fetch transform code
        run: |
          wget https://raw.githubusercontent.com/nunit/nunit-transforms/master/nunit3-junit/nunit3-junit.xslt
        shell: bash
        
      - name: Download test artifact
        uses: actions/download-artifact@v4.1.2
        with:
          name: test-results   
          path: ./report

      - name: Delete test artifact
        uses: geekyeggo/delete-artifact@v4.1.0
        with:
           name: test-results
           token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install NUnit
        run: |
          nuget install NUnit.Console -Version 3.16.3
        shell: bash
        
      - name: Transform NUnit3 to JUnit
        run: |
          $xml = Resolve-Path "report/TestResults.xml" # Replace with your specific file name
          $output = Join-Path ($pwd.Path) "report/${{ env.TEST_PROJECT_NAME }}.xml" # Output file name
          $xslt = New-Object System.Xml.Xsl.XslCompiledTransform;
          $xslt.Load("nunit3-junit.xslt");
          $xslt.Transform($xml, $output);
        shell: pwsh

      - name: Publish report
        uses: dorny/test-reporter@v1.8.0
        with:
          name: "test-reports"
          path: "report/${{ env.TEST_PROJECT_NAME }}.xml"
          reporter: jest-junit
