name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
  
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2.3.4

     - name: Fetch transform code
       run: |
          wget https://raw.githubusercontent.com/nunit/nunit-transforms/master/nunit3-junit/nunit3-junit.xslt
       shell: bash
        
     - name: Download test artifact
       uses: actions/download-artifact@v4.1.1
       with:
         name: FFF.Clipboard.Tests
         path: report    
     
     - name: Install NUnit.Console
       run: |
          nuget install NUnit.Console -Version 3.12.0
       shell: bash

        
